---
# vars file for satellite
satellite_local_manifest_path: "/path_to/satellite_manifest.zip" # local path to the satellite manifest file

satellite_organization: My_Organization
satellite_location: Tokyo
satellite_admin_username: admin # usually don't need to be changed
satellite_manifest_path: "/root/satellite_manifest.zip" # path to the satellite manifest file uploaded
satellite_content_view: "RHEL9_SOE" # usually don't need to be changed
satellite_cv_initial_end_date: "2024-04-30" # this date depends on when RHEL9 golden image is created
satellite_activation_key_name: "Demo_Key" # usually don't need to be changed
